### ISSUE TITLE
mkdir: missing operand

### ISSUE THREAD

**Issue by infosecsecurity** [UltimateHackers/Photon#1]
I'm getting this mkdir: missing operand. Any idea?
![screenshot from 2018-03-31 12-03-03](https://user-images.githubusercontent.com/7826342/38164459-8f8cdb90-34db-11e8-9f8e-d64d00f79ae2.png)

**Comment by UltimateHackers** [comment]
If you can send me the target that would be really helpful to recreate this issue. You can mail me at s0md3v@gmail.com or dm on Twitter at @s0md3v
