### ISSUE TITLE
How to Save Results

### ISSUE THREAD

**Issue by attacker420** [UltimateHackers/Photon#2]
Dear Team,

Tool is awesome but when I tried running your command like:

Python photon.py http://site.com --delay=1.5

I got result like this one:

```
      ____  __          __            
     / __ \/ /_  ____  / /_____  ____ 
    / /_/ / __ \/ __ \/ __/ __ \/ __ \
   / ____/ / / / /_/ / /_/ /_/ / / / /
  /_/   /_/ /_/\____/\__/\____/_/ /_/ 

[!] Links to crawl: 108
[!] Time required: ~5 minutes
[+] Total URLs found: 780
[+] Fuzzable URLs found: 149
[+] JavaScript files found: 126
[~] Scanning JavaScript files for endpoints
[!] Time required: ~1 minute
[+] Enpoints found: 346
mkdir: missing operand
Try 'mkdir --help' for more information.
[+] Results saved in  directory

```

i don't know where results are being saved.

Can you please update the READme file.

Thanks.

**Comment by UltimateHackers** [comment]
The results are saved automatically. If you can send me the target that would be really helpful to recreate this issue. You can mail me at s0md3v@gmail.com or dm on Twitter at @s0md3v
Thanks in advance
